### ISSUE TITLE
Parameters not handled correctly

### ISSUE THREAD

**Issue by egilll** [tripolskypetr/react-history-switch#1]
Hello, I am opening this issue mainly to allow others who come across this to be aware of the problem, but I am not expecting that it be fixed.

The issue is that the library only supports having a single route with parameters. An example:

```js

const First = (params) => {
  console.log(params);
  return null;
};
const Second = (params) => {
   console.log(params);
  return null;
};
const Third = (params) => {
  console.log(params);
  return null;
};

const items = [
  {
    path: "/first/:param1",
    component: First,
  },
  {
    path: "/second/:param2",
    component: Second,
  },
  {
    path: "/third/:param3",
    component: Third,
  },
];

export const Routes = () => {
  return <Switch items={items} history={history} />;
};
```

If one opens the URL `/third/123`, it will output: 

```js
{param1: '123', param2: undefined, param3: undefined}
```

instead of the expected:

```
{param3: '123'}
```

I believe this is due to [`const keys: Key[] = [];`](https://github.com/tripolskypetr/react-history-switch/blob/3d434d548e4b19f1b016ce8d75817b11ac7be501/src/utils/getItem.ts#L18) being in the outer lexical scope instead of inside `items.reduce`, but I haven't tried it.

I did end up using the library [url-pattern](https://github.com/snd/url-pattern) instead.

**Comment by tripolskypetr** [comment]
The development of this router was continued at [react-declarative](https://npmjs.org/package/react-declarative). For backward compability, I commited [the patch](https://github.com/react-declarative/react-declarative/blob/3f5eeb3ba7546221c0a981312bb4764c4514195d/src/components/Switch/Switch.tsx#L105) in this repo too
